library(tidyverse)
library(dplyr)

select_mags <- list("I4_MAG_00006", "I4_MAG_00065", "L3_MAG_00058", "L8_MAG_00011", "L8_MAG_00019")
other_mags <- list ("L2_MAG_00052", "L4_MAG_00099", "L7_MAG_00020", "L7_MAG_00028", "L7_MAG_00043", "L8_MAG_00042")
EPSPS_class_1 <- list("I4_MAG_00006", "L7_MAG_00028", "L8_MAG_00011", "L8_MAG_00019", "L8_MAG_00042", "L2_MAG_00052", "L4_MAG_00099", "L7_MAG_00020")
EPSPS_class_2 <- list("I4_MAG_00065", "L3_MAG_00058", "L7_MAG_00043")

sig_genes_loose <- read_csv("significant_genes_loose_all_subsamp.csv")
sig_genes_strict <- read_csv("significant_genes_strict_all_subsamp.csv")
sig_genes_threshold <- read_csv("threshold_significant_genes_all_subsamp.csv")
sig_genes_increase <- read_csv("gene_cov_sig_increase_all_subsamp.csv")
sig_genes_increase$mag <- sig_genes_increase$gene %>% substr(1,12)
sig_genes_decrease <- read_csv("gene_cov_sig_decrease_all_subsamp.csv")
sig_genes_decrease$mag <- sig_genes_decrease$gene %>% substr(1,12)

#by EPSPS class
sig_genes_loose_C1 <- subset(sig_genes_loose, mag %in% EPSPS_class_1)
sig_genes_strict_C1 <- subset(sig_genes_strict, mag %in% EPSPS_class_1)
sig_genes_threshold_C1 <- subset(sig_genes_threshold, mag %in% EPSPS_class_1)
sig_genes_increase_C1 <- subset(sig_genes_increase, mag %in% EPSPS_class_1)
sig_genes_decrease_C1 <- subset(sig_genes_decrease, mag %in% EPSPS_class_1)

write.csv(sig_genes_loose_C1, "sig_genes_loose_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_C1, "sig_genes_strict_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_C1, "sig_genes_threshold_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_C1, "sig_genes_increase_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_C1, "sig_genes_decrease_C1_subsamp.csv", row.names = F)

sig_genes_loose_C2 <- subset(sig_genes_loose, mag %in% EPSPS_class_2)
sig_genes_strict_C2 <- subset(sig_genes_strict, mag %in% EPSPS_class_2)
sig_genes_threshold_C2 <- subset(sig_genes_threshold, mag %in% EPSPS_class_2)
sig_genes_increase_C2 <- subset(sig_genes_increase, mag %in% EPSPS_class_2)
sig_genes_decrease_C2 <- subset(sig_genes_decrease, mag %in% EPSPS_class_2)

write.csv(sig_genes_loose_C2, "sig_genes_loose_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_C2, "sig_genes_strict_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_C2, "sig_genes_threshold_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_C2, "sig_genes_increase_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_C2, "sig_genes_decrease_C2_subsamp.csv", row.names = F)

#by sweep
sig_genes_loose_sweep <- subset(sig_genes_loose, mag %in% select_mags)
sig_genes_strict_sweep <- subset(sig_genes_strict, mag %in% select_mags)
sig_genes_threshold_sweep <- subset(sig_genes_threshold, mag %in% select_mags)
sig_genes_increase_sweep <- subset(sig_genes_increase, mag %in% select_mags)
sig_genes_decrease_sweep <- subset(sig_genes_decrease, mag %in% select_mags)

write.csv(sig_genes_loose_sweep, "sig_genes_loose_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_sweep, "sig_genes_strict_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_sweep, "sig_genes_threshold_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_sweep, "sig_genes_increase_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_sweep, "sig_genes_decrease_sweep_subsamp.csv", row.names = F)

sig_genes_loose_no_sweep <- subset(sig_genes_loose, mag %in% other_mags)
sig_genes_strict_no_sweep <- subset(sig_genes_strict, mag %in% other_mags)
sig_genes_threshold_no_sweep <- subset(sig_genes_threshold, mag %in% other_mags)
sig_genes_increase_no_sweep <- subset(sig_genes_increase, mag %in% other_mags)
sig_genes_decrease_no_sweep <- subset(sig_genes_decrease, mag %in% other_mags)

write.csv(sig_genes_loose_no_sweep, "sig_genes_loose_no_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_no_sweep, "sig_genes_strict_no_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_no_sweep, "sig_genes_threshold_no_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_no_sweep, "sig_genes_increase_no_sweep_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_no_sweep, "sig_genes_decrease_no_sweep_subsamp.csv", row.names = F)
