library(tidyverse)
library(dplyr)

EPSPS_class_1 <- list("I4_MAG_00006", "L7_MAG_00028", "L8_MAG_00011", "L8_MAG_00019", "L8_MAG_00042")
EPSPS_class_2 <- list("I4_MAG_00065", "L3_MAG_00058", "L7_MAG_00020", "L7_MAG_00043")

sig_genes_loose <- read_csv("significant_genes_loose_all_subsamp.csv")
sig_genes_loose_pos <- read_csv("SNV_decrease_genes.csv")
sig_genes_loose_neg <- read_csv("SNV_increase_genes.csv")

sig_genes_strict <- read_csv("significant_genes_strict_all_subsamp.csv")
sig_genes_strict_pos <- read_csv("parallel_decrease_genes.csv")
sig_genes_strict_neg <- read_csv("parallel_increase_genes.csv")

sig_genes_threshold <- read_csv("threshold_significant_genes_all_subsamp.csv")
sig_genes_increase <- read_csv("gene_cov_sig_increase_all_subsamp.csv")
sig_genes_decrease <- read_csv("gene_cov_sig_decrease_all_subsamp.csv")

#by EPSPS class
sig_genes_loose_pos_C1 <- subset(sig_genes_loose_pos, mag %in% EPSPS_class_1)
sig_genes_loose_neg_C1 <- subset(sig_genes_loose_neg, mag %in% EPSPS_class_1)
sig_genes_strict_pos_C1 <- subset(sig_genes_strict_pos, mag %in% EPSPS_class_1)
sig_genes_strict_neg_C1 <- subset(sig_genes_strict_neg, mag %in% EPSPS_class_1)
sig_genes_threshold_C1 <- subset(sig_genes_threshold, mag %in% EPSPS_class_1)
sig_genes_increase_C1 <- subset(sig_genes_increase, mag %in% EPSPS_class_1)
sig_genes_decrease_C1 <- subset(sig_genes_decrease, mag %in% EPSPS_class_1)

write.csv(sig_genes_loose_pos_C1, "sig_genes_loose_pos_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_loose_neg_C1, "sig_genes_loose_neg_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_pos_C1, "sig_genes_strict_pos_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_neg_C1, "sig_genes_strict_neg_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_C1, "sig_genes_threshold_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_C1, "sig_genes_increase_C1_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_C1, "sig_genes_decrease_C1_subsamp.csv", row.names = F)

sig_genes_loose_pos_C2 <- subset(sig_genes_loose_pos, mag %in% EPSPS_class_2)
sig_genes_loose_neg_C2 <- subset(sig_genes_loose_neg, mag %in% EPSPS_class_2)
sig_genes_strict_pos_C2 <- subset(sig_genes_strict_pos, mag %in% EPSPS_class_2)
sig_genes_strict_neg_C2 <- subset(sig_genes_strict_neg, mag %in% EPSPS_class_2)
sig_genes_threshold_C2 <- subset(sig_genes_threshold, mag %in% EPSPS_class_2)
sig_genes_increase_C2 <- subset(sig_genes_increase, mag %in% EPSPS_class_2)
sig_genes_decrease_C2 <- subset(sig_genes_decrease, mag %in% EPSPS_class_2)

write.csv(sig_genes_loose_pos_C2, "sig_genes_loose_pos_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_loose_neg_C2, "sig_genes_loose_neg_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_pos_C2, "sig_genes_strict_pos_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_strict_neg_C2, "sig_genes_strict_neg_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_threshold_C2, "sig_genes_threshold_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_increase_C2, "sig_genes_increase_C2_subsamp.csv", row.names = F)
write.csv(sig_genes_decrease_C2, "sig_genes_decrease_C2_subsamp.csv", row.names = F)
